# This is a basic workflow to help you get started with Actions

name: Ansible, Github, PyGithub Workflow

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    paths:
    - 'src/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
            pip install ansible
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN }}
        run: |
          pip install PyGithub
          pip install --upgrade PyGitHub
          chmod +x "${GITHUB_WORKSPACE}/.github/script.sh"
          "${GITHUB_WORKSPACE}/.github/script.sh"
